export const ASSETS = {
  base: "assets/base_map.png",
  overlays: {
    "Papua Barat": "assets/regions/region-pabar-min.webp",
    "Papua Tengah": "assets/regions/region-pateng-min.webp",
    "Papua Selatan": "assets/regions/region-pasel-min.webp",
    Papua: "assets/regions/region-papua-min.webp",
    "Papua Pegunungan": "assets/regions/region-pagu-min.webp",
    Maluku: "assets/regions/region-maluku-min.webp",
    "Maluku Utara": "assets/regions/region-maltara-min.webp",
    "Sulawesi Tenggara": "assets/regions/region-sultengara-min.webp",
    "Sulawesi Selatan": "assets/regions/region-sulsel-min.webp",
    "Sulawesi Barat": "assets/regions/region-sulbar-min.webp",
    "Sulawesi Tengah": "assets/regions/region-sulteng-min.webp",
    Gorontalo: "assets/regions/region-gorontalo-min.webp",
    "Sulawesi Utara": "assets/regions/region-sultara-min.webp",
    "Kalimantan Utara": "assets/regions/region-kaltara-min.webp",
    "Kalimantan Timur": "assets/regions/region-kaltim-min.webp",
    "Kalimantan Selatan": "assets/regions/region-kalsel-min.webp",
    "Kalimantan Tengah": "assets/regions/region-kalteng-min.webp",
    "Kalimantan Barat": "assets/regions/region-kalbar-min.webp",
    "Nusa Tenggara Timur": "assets/regions/region-ntt-min.webp",
    "Nusa Tenggara Barat": "assets/regions/region-ntb-min.webp",
    Bali: "assets/regions/region-bali-min.webp",
    "Jawa Timur": "assets/regions/region-jatim-min.webp",
    "Daerah Istimewa Yogyakarta": "assets/regions/region-diy-min.webp",
    "Jawa Tengah": "assets/regions/region-jateng-min.webp",
    "Jawa Barat": "assets/regions/region-jabar-min.webp",
    "Daerah Khusus Jakarta": "assets/regions/region-dki-jakarta-min.webp",
    Banten: "assets/regions/region-banten-min.webp",
    "Kepulauan Bangka Belitung": "assets/regions/region-kep-bangka-min.webp",
    Lampung: "assets/regions/region-lampung-min.webp",
    Bengkulu: "assets/regions/region-bengkulu-min.webp",
    "Sumatera Selatan": "assets/regions/region-sumsel-min.webp",
    Jambi: "assets/regions/region-jambi-min.webp",
    "Kepulauan Riau": "assets/regions/region-kep-riau-min.webp",
    Riau: "assets/regions/region-riau-min.webp",
    "Sumatera Barat": "assets/regions/region-sumbar-min.webp",
    "Sumatera Utara": "assets/regions/region-sumut-min.webp",
    Aceh: "assets/regions/region-aceh-min.webp",
  },
  icons: {
    "Papua Barat": "assets/icons/icon-pabar-min.webp",
    "Papua Tengah": "assets/icons/icon-pateng-min.webp",
    "Papua Selatan": "assets/icons/icon-pasel-min.webp",
    Papua: "assets/icons/icon-papua-min.webp",
    "Papua Pegunungan": "assets/icons/icon-pagu-min.webp",
    Maluku: "assets/icons/icon-maluku-min.webp",
    "Maluku Utara": "assets/icons/icon-malutara-min.webp",
    "Sulawesi Tenggara": "assets/icons/icon-sulteng-min.webp",
    "Sulawesi Selatan": "assets/icons/icon-sulsel-min.webp",
    "Sulawesi Barat": "assets/icons/icon-sulbar-min.webp",
    "Sulawesi Tengah": "assets/icons/icon-sultengah-min.webp",
    Gorontalo: "assets/icons/icon-gorontalo-min.webp",
    "Sulawesi Utara": "assets/icons/icon-sultara-min.webp",
    "Kalimantan Utara": "assets/icons/icon-kaltara-min.webp",
    "Kalimantan Timur": "assets/icons/icon-kaltim-min.webp",
    "Kalimantan Selatan": "assets/icons/icon-kalsel-min.webp",
    "Kalimantan Tengah": "assets/icons/icon-kalteng-min.webp",
    "Kalimantan Barat": "assets/icons/icon-kalbar-min.webp",
    "Nusa Tenggara Timur": "assets/icons/icon-ntt-min.webp",
    "Nusa Tenggara Barat": "assets/icons/icon-ntb-min.webp",
    Bali: "assets/icons/icon-bali-min.webp",
    "Jawa Timur": "assets/icons/icon-jatim-min.webp",
    "Daerah Istimewa Yogyakarta": "assets/icons/icon-diy-min.webp",
    "Jawa Tengah": "assets/icons/icon-jateng-min.webp",
    "Jawa Barat": "assets/icons/icon-jabar-min.webp",
    "Daerah Khusus Jakarta": "assets/icons/icon-dki-jakarta-min.webp",
    Banten: "assets/icons/icon-banten-min.webp",
    "Kepulauan Bangka Belitung": "assets/icons/icon-kep-bangka-min.webp",
    Lampung: "assets/icons/icon-lampung-min.webp",
    Bengkulu: "assets/icons/icon-bengkulu-min.webp",
    "Sumatera Selatan": "assets/icons/icon-sumsel-min.webp",
    Jambi: "assets/icons/icon-jambi-min.webp",
    "Kepulauan Riau": "assets/icons/icon-kep-riau-min.webp",
    Riau: "assets/icons/icon-riau-min.webp",
    "Sumatera Barat": "assets/icons/icon-sumbar-min.webp",
    "Sumatera Utara": "assets/icons/icon-sumut-min.webp",
    Aceh: "assets/icons/icon-aceh-min.webp",
  },
  sounds: {
    hoverSfx: "assets/musics/sfx-hover.mp3",
    clickSfx: "assets/musics/sfx-click.mp3",
    bgMusic: "assets/musics/bg-music.mp3",
  },
};
